### ISSUE TITLE
Assistant breaks if JS selected

### ISSUE THREAD

**Issue by fila90** [Unibeautify/assistant#153]
As title says, If you choose JavaScript as a language and click `Next`, assistant breaks.
Also for every language `align_assignments.txt` can't be found.

**EDIT**
After more exploration, error occurs every time assistant tries to load more content
e.g.
`CSS > Indent Size`

**Comment by Glavin001** [comment]
I can reproduce:

![image](https://user-images.githubusercontent.com/1885333/54683367-38610680-4af0-11e9-958d-02ead3bbb5d8.png)

Thank you for reporting this issue!

**Comment by Glavin001** [comment]
Pull Requests welcome!

**Comment by stevenzeck** [comment]
That's not good. I'll look into this tonight

**Comment by stevenzeck** [comment]
Something about [react-highlight](https://github.com/akiran/react-highlight) does not agree with the newer versions of React and/or its supporting packages.

**Comment by stevenzeck** [comment]
@fila90 please try now

**Comment by Glavin001** [comment]
Looks like there's still a problem: https://assistant.unibeautify.com/#/setup

![image](https://user-images.githubusercontent.com/1885333/54729619-5e73be80-4b63-11e9-89ba-cf486ea9acb8.png)

**Comment by stevenzeck** [comment]
@Glavin001 I don't get that error.
![Screen Shot 2019-03-20 at 9 09 33 PM](https://user-images.githubusercontent.com/8315038/54730022-7db71f80-4b54-11e9-8ae6-fc01e0cd1784.png)

**Comment by fila90** [comment]
Works now, although there's error 
![Screenshot from 2019-03-21 09-49-18](https://user-images.githubusercontent.com/16494464/54743012-46cc2280-4bc3-11e9-9c20-a0fe983792f2.png)


1.  Is there any **simpler/global** way to edit some settings?
e.g. `indent_size` is set to 2 for all languages, is there a way I can set it once and it applies for every language I selected?


2. You also have a tiny bug wit `.yaml` files
if you toggle an option e.g. `jsx_brackets` for JSON (??)  `default` => `true` => `default`
`yaml` config will look like this
``` yaml
JSON
  jsx_brackets: !<tag:yaml.org,2002:js/undefined> '' 
```
`.json` config stays pristine.

3. If you try to install plugin trough VS Code interface, smiley faces aren't parsed properly so you're left of with `:zap:`

4. Config for default configuration doesn't work for me, after reboot I get an error saying it can't find the file
VS Code: `1.32.3`
OS: `Pop!_OS 18.10`
```"unibeautify.defaultConfig": "/home/ivan/Downloads/unibeautifyrc.yaml"```

5. And one last question (I hope :grin:) 
what is an Multiline Ternary in CSS? and why there is not one for Vue? (and other weird combinations of rules and options)

Sorry for writing it all here, if you want I can raise issues separately, but since you're all here :grin: 

Great tool by the way, I was struggling between `prettier` and `JS-beautify` and now I can have both and much more! :tada: :tada:

**Comment by stevenzeck** [comment]
Ah, it again throws a console error when going through the wizard. Again, when there are code examples that should be showing.

**Comment by stevenzeck** [comment]
Ok, it has nothing to do with Highlight. Node's `[require](https://github.com/Unibeautify/assistant/blob/master/src/UglySamples.ts#L6)` function is returning more than just the file contents.
![screen_shot_2019-03-21_at_7 35 04_pm](https://user-images.githubusercontent.com/8315038/54826949-ec909780-4c7e-11e9-8eb5-d3c45c61b23f.png)

**Comment by stevenzeck** [comment]
OK, now it's really fixed.  @fila90 I'll come back to your [question](https://github.com/Unibeautify/assistant/issues/153#issuecomment-475167561) in a bit.

**Comment by Glavin001** [comment]
Looks good. Great work, @stevenzeck ! 🎉 

![image](https://user-images.githubusercontent.com/1885333/54871094-ef2de280-4d8d-11e9-95c8-50e07d9d4f76.png)

**Comment by fila90** [comment]
wooow 😮
those examples are extremely useful, great job!! 🎉🎉
